function [Stk,delta_u,x]=Sample_MPPI_CartPole(...
                            K,N,variance,Stk,...
                            x,delta_u,u,...
                            R, mc, mp, l, g, kd, dt...
                            )
        for k = 1:K
            [Stk,delta_u,x]=...
                sampleTraj_MPPI_CartPole(...
                                    k,N,variance,Stk,...
                                    x,delta_u,u,...
                                    R, mc, mp, l, g, kd, dt...
                                    );
             delta_u(N,k) = variance*(randn(1));
        end     
end % end function